
import { jsPDF } from 'jspdf';

type Props = {
  pdfReady: boolean;
  onDownload: () => void;
  onEmail: () => void;
  onBack: () => void;
};

const OutputSection = ({ pdfReady, onDownload, onEmail, onBack }: Props) => {
  const handleDownloadPDF = () => {
    // Create a new PDF document
    const doc = new jsPDF();
    
    // Add title
    doc.setFontSize(16);
    doc.text('SCC Form - Generated Document', 20, 20);
    
    // Add form content (this would be replaced with actual form data)
    doc.setFontSize(12);
    doc.text('Court File Number: CV-2024-001234', 20, 40);
    doc.text('Form Type: Form 25 - Affidavit', 20, 50);
    doc.text('Generated on: ' + new Date().toLocaleDateString(), 20, 60);
    
    // Add some sample form fields
    doc.text('Plaintiff: John Smith', 20, 80);
    doc.text('Defendant: ABC Company Ltd.', 20, 90);
    doc.text('Amount Claimed: $5,000.00', 20, 100);
    
    // Add footer
    doc.setFontSize(10);
    doc.text('Generated by SCC Form Filler - For demo purposes only', 20, 280);
    
    // Download the PDF
    doc.save('scc-form-filled.pdf');
    
    // Call the original onDownload callback
    onDownload();
  };

  return (
    <div className="flex flex-col items-center gap-7 justify-center min-h-[180px]">
      {!pdfReady ? (
        <>
          <div className="flex items-center gap-2 text-blue-700 font-medium text-lg">
            <span className="animate-spin inline-block w-6 h-6 border-t-2 border-b-2 border-blue-600 rounded-full mr-2"></span>
            Generating your PDF…
          </div>
          <div className="text-sm text-muted-foreground">
            This may take a few seconds. Please wait.
          </div>
        </>
      ) : (
        <>
          <div className="flex flex-col items-center gap-3">
            <span className="text-green-700 text-2xl font-semibold">
              ✅ PDF is ready!
            </span>
            <div className="flex gap-4 justify-center flex-wrap mt-2">
              <button
                className="px-5 py-2 rounded-lg bg-primary text-white hover:bg-blue-800 font-semibold shadow transition"
                onClick={handleDownloadPDF}
              >
                Download PDF
              </button>
              <button
                className="px-5 py-2 rounded-lg bg-secondary text-primary hover:bg-accent font-semibold shadow transition"
                onClick={onEmail}
              >
                Email Output
              </button>
            </div>
          </div>
          <button
            className="px-4 py-1 rounded border border-border text-muted-foreground mt-6 hover:bg-muted"
            onClick={onBack}
          >
            Back to Input
          </button>
        </>
      )}
    </div>
  );
};

export default OutputSection;
